{
  "Title": "Security update for python-Django",
  "Tracking": {
    "ID": "SUSE-SU-2024:3187-1",
    "Status": "Final",
    "Version": "1",
    "InitialReleaseDate": "2024-09-10T08:44:31Z",
    "CurrentReleaseDate": "2024-09-10T08:44:31Z",
    "RevisionHistory": [
      {
        "Number": "1",
        "Date": "2024-09-10T08:44:31Z",
        "Description": "current"
      }
    ]
  },
  "Notes": [
    {
      "Text": "Security update for python-Django",
      "Title": "Topic",
      "Type": "Summary"
    },
    {
      "Text": "This update for python-Django fixes the following issues:\n\nThere is an issue with the previous fix for CVE-2024-45230. Please consider the following vulnerability fixed only after the installation of this update.\n  - CVE-2024-45230: Fixed potential denial-of-service vulnerability in django.utils.html.urlize(). (bsc#1229823)\n",
      "Title": "Details",
      "Type": "General"
    },
    {
      "Text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
      "Title": "Terms of Use",
      "Type": "Legal Disclaimer"
    },
    {
      "Text": "SUSE-2024-3187,openSUSE-SLE-15.5-2024-3187",
      "Title": "Patchnames",
      "Type": "Details"
    }
  ],
  "ProductTree": {
    "Relationships": [
      {
        "ProductReference": "python3-Django-2.0.7-150000.1.36.1",
        "RelatesToProductReference": "openSUSE Leap 15.5",
        "RelationType": "Default Component Of"
      }
    ]
  },
  "References": [
    {
      "URL": "https://www.suse.com/support/update/announcement/2024/suse-su-20243187-1/",
      "Description": "Link for SUSE-SU-2024:3187-1"
    },
    {
      "URL": "https://lists.suse.com/pipermail/sle-security-updates/2024-September/019406.html",
      "Description": "E-Mail link for SUSE-SU-2024:3187-1"
    },
    {
      "URL": "https://www.suse.com/support/security/rating/",
      "Description": "SUSE Security Ratings"
    },
    {
      "URL": "https://bugzilla.suse.com/1229823",
      "Description": "SUSE Bug 1229823"
    },
    {
      "URL": "https://www.suse.com/security/cve/CVE-2024-45230/",
      "Description": "SUSE CVE CVE-2024-45230 page"
    }
  ],
  "Vulnerabilities": [
    {
      "CVE": "CVE-2024-45230",
      "Description": "** RESERVED ** This candidate has been reserved by an organization or individual that will use it when announcing a new security problem. When the candidate has been publicized, the details for this candidate will be provided.",
      "Threats": [
        {
          "Type": "Impact",
          "Severity": "important"
        }
      ],
      "References": [
        {
          "URL": "https://www.suse.com/security/cve/CVE-2024-45230.html",
          "Description": "CVE-2024-45230"
        },
        {
          "URL": "https://bugzilla.suse.com/1229823",
          "Description": "SUSE Bug 1229823"
        }
      ],
      "ProductStatuses": [
        {
          "Type": "Fixed",
          "ProductID": [
            "openSUSE Leap 15.5:python3-Django-2.0.7-150000.1.36.1"
          ]
        }
      ],
      "CVSSScoreSets": {}
    }
  ]
}