{
  "PublicDateAtUSN": "0001-01-01T00:00:00Z",
  "CRD": "0001-01-01T00:00:00Z",
  "Candidate": "CVE-2016-4807",
  "PublicDate": "2024-08-12T00:00:00Z",
  "References": [
    "https://www.cve.org/CVERecord?id=CVE-2016-4807",
    "https://github.com/web2py/web2py/issues/1585",
    "https://github.com/web2py/web2py/commit/51c3b633fe7ad647bc3013e899c1e3a910362dd1"
  ],
  "Description": "(Web2py versions 2.14.5 and below was affected by Reflected XSS vulnera ...)",
  "UbuntuDescription": "",
  "Notes": null,
  "Bugs": [
    "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=856127"
  ],
  "Priority": "medium",
  "DiscoveredBy": "",
  "AssignedTo": "",
  "Patches": {
    "web2py": {
      "devel": {
        "Status": "DNE",
        "Note": ""
      },
      "esm-apps/xenial": {
        "Status": "needs-triage",
        "Note": ""
      },
      "focal": {
        "Status": "DNE",
        "Note": ""
      },
      "jammy": {
        "Status": "DNE",
        "Note": ""
      },
      "noble": {
        "Status": "DNE",
        "Note": ""
      },
      "upstream": {
        "Status": "needs-triage",
        "Note": ""
      }
    }
  },
  "UpstreamLinks": {}
}