{
  "id": "PYSEC-2022-43151",
  "modified": "2024-11-21T14:22:59.956918Z",
  "published": "2022-12-19T22:15:00Z",
  "withdrawn": "2024-11-22T04:37:05Z",
  "details": "Patchelf v0.9 was discovered to contain an out-of-bounds read via the function modifyRPath at src/patchelf.cc.",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pypatchelf",
        "purl": "pkg:pypi/pypatchelf"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            }
          ]
        }
      ],
      "versions": [
        "0.8",
        "0.9"
      ],
      "database_specific": {
        "source": "https://github.com/pypa/advisory-database/blob/main/vulns/pypatchelf/PYSEC-2022-43151.yaml"
      }
    }
  ],
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/NixOS/patchelf/pull/419"
    }
  ]
}