{
  "id": "MAL-2024-8017",
  "modified": "2024-08-11T18:07:20Z",
  "published": "2024-08-11T12:41:52Z",
  "summary": "Malicious code in artifact-lab-3-package-392c6acd (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n\n## Source: ossf-package-analysis (b04b33fa38a07736307a011b99bada5213399f1d9a84780fde87d35379149bf1)\nThe OpenSSF Package Analysis project identified 'artifact-lab-3-package-392c6acd' @ 0.1.0 (pypi) as malicious.\n\nIt is considered malicious because:\n\n- The package communicates with a domain associated with malicious activity.\n\n- The package executes one or more commands associated with malicious behavior.\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "artifact-lab-3-package-392c6acd",
        "purl": "pkg:pypi/artifact-lab-3-package-392c6acd"
      },
      "versions": [
        "0.1.0",
        "0.1.1",
        "0.1.3",
        "0.1.2",
        "0.1.4",
        "0.1.5",
        "0.1.6",
        "0.1.12",
        "0.1.7"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/artifact-lab-3-package-392c6acd/MAL-2024-8017.json"
      }
    }
  ]
}