{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2023-29935"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "llvm-project commit a0138390 was discovered to contain an assertion failure at !replacements.count(op) \u0026\u0026 \"operation was already replaced."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://github.com/llvm/llvm-project/issues/59182",
          "refsource": "MISC",
          "tags": [],
          "url": "https://github.com/llvm/llvm-project/issues/59182"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2023-05-05T16:27Z",
  "publishedDate": "2023-05-05T15:15Z"
}