{
  "PublicDateAtUSN": "0001-01-01T00:00:00Z",
  "CRD": "2025-03-06T13:00:00Z",
  "Candidate": "CVE-2025-26699",
  "PublicDate": "2025-03-06T13:00:00Z",
  "References": [
    "https://www.cve.org/CVERecord?id=CVE-2025-26699"
  ],
  "Description": "Potential denial-of-service vulnerability in django.utils.text.wrap()",
  "UbuntuDescription": "",
  "Notes": null,
  "Bugs": null,
  "Priority": "medium",
  "DiscoveredBy": "",
  "AssignedTo": "hlibk",
  "Patches": {
    "python-django": {
      "devel": {
        "Status": "needs-triage",
        "Note": ""
      },
      "esm-infra-legacy/trusty": {
        "Status": "needs-triage",
        "Note": ""
      },
      "esm-infra/bionic": {
        "Status": "needs-triage",
        "Note": ""
      },
      "esm-infra/xenial": {
        "Status": "needs-triage",
        "Note": ""
      },
      "focal": {
        "Status": "needs-triage",
        "Note": ""
      },
      "jammy": {
        "Status": "needs-triage",
        "Note": ""
      },
      "noble": {
        "Status": "needs-triage",
        "Note": ""
      },
      "oracular": {
        "Status": "needs-triage",
        "Note": ""
      },
      "upstream": {
        "Status": "released",
        "Note": "5.1.7,5.0.13,4.2.20"
      }
    }
  },
  "UpstreamLinks": {}
}