{
  "Identifier": "GHSA-pp84-v3mw-gg4w",
  "PackageSlug": "pypi/taipy",
  "Title": "Taipy 3.1.1 affected by CVEs on flask-core and pymongo",
  "Description": "CVEs on latest 3.1.1",
  "Date": "2024-08-27",
  "Pubdate": "2024-08-27",
  "AffectedRange": "\u003c=3.1.1",
  "FixedVersions": [],
  "AffectedVersions": "All versions up to 3.1.1",
  "NotImpacted": "",
  "Solution": "Unfortunately, there is no solution available yet.",
  "Urls": [
    "https://github.com/advisories/GHSA-pp84-v3mw-gg4w",
    "https://github.com/Avaiga/taipy/security/advisories/GHSA-pp84-v3mw-gg4w",
    "https://github.com/Avaiga/taipy"
  ],
  "CvssV2": "",
  "CvssV3": "",
  "UUID": "c5b7062b-f9e9-4f87-a4c5-cf0965895e3d"
}