{
  "Severity": "CRITICAL",
  "UpdatedAt": "2021-08-19T21:19:54Z",
  "Package": {
    "Ecosystem": "RUST",
    "Name": "failure"
  },
  "Advisory": {
    "DatabaseId": 5255,
    "Id": "MDE2OlNlY3VyaXR5QWR2aXNvcnlHSFNBLXI5OHItajI1cS1ybXBy",
    "GhsaId": "GHSA-r98r-j25q-rmpr",
    "References": [
      {
        "Url": "https://nvd.nist.gov/vuln/detail/CVE-2019-25010"
      },
      {
        "Url": "https://github.com/rust-lang-nursery/failure/issues/336"
      },
      {
        "Url": "https://rustsec.org/advisories/RUSTSEC-2019-0036.html"
      },
      {
        "Url": "https://github.com/advisories/GHSA-r98r-j25q-rmpr"
      }
    ],
    "Identifiers": [
      {
        "Type": "GHSA",
        "Value": "GHSA-r98r-j25q-rmpr"
      },
      {
        "Type": "CVE",
        "Value": "CVE-2019-25010"
      }
    ],
    "Description": "An issue was discovered in the failure crate through 2019-11-13 for Rust. Type confusion can occur when __private_get_type_id__ is overridden.",
    "Origin": "UNSPECIFIED",
    "PublishedAt": "2021-08-25T20:46:38Z",
    "Severity": "CRITICAL",
    "Summary": "Type confusion in failure",
    "UpdatedAt": "2023-01-09T05:05:36Z",
    "WithdrawnAt": "",
    "CVSS": {
      "Score": 9.8,
      "VectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  },
  "Versions": [
    {
      "FirstPatchedVersion": {
        "Identifier": ""
      },
      "VulnerableVersionRange": "\u003c= 0.1.8"
    }
  ]
}